openapi: 3.0.0
info:
  title: echo-mona
  version: 1.0.0
servers:
- url: "http://{{host}}"
paths:
  /api/{version}/saas/suspend:
    post:
      parameters:
      - example: "{{api_version}}"
        explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                id: <guid>
                activityId: <guid>
                publisherId: testpublisher
                offerId: testoffer
                planId: starter
                quantity: 1
                subscriptionId: <guid>
                timeStamp: 2022-03-10T16:34:41.137017Z
                action: Suspend
                status: Succeeded
                operationRequestSource: Azure
                subscription:
                  id: <guid>
                  name: testcms
                  publisherId: testpublisher
                  offerId: cmstestoffer
                  planId: starter
                  quantity: null
                  beneficiary:
                    emailId: XXX
                    objectId: <guid>
                    tenantId: <guid>
                    puid: XXX
                  purchaser:
                    emailId: XXX
                    objectId: <guid>
                    tenantId: <guid>
                    puid: XXX
                  allowedCustomerOperations:
                  - Delete
                  - Update
                  - Read
                  sessionMode: None
                  isFreeTrial: false
                  isTest: false
                  sandboxType: None
                  saasSubscriptionStatus: Subscribed
                  term:
                    startDate: 2022-03-09T00:00:00Z
                    endDate: 2022-04-08T00:00:00Z
                    termUnit: P1M
                    chargeDuration: null
                  autoRenew: true
                  created: 2022-03-09T18:45:49.0735944Z
                  lastModified: 2022-03-09T22:49:25.4181451Z
                purchaseToken: null
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: suspend - POST
      tags:
      - default
  /api/{version}/saas/purchased/{subscription-id}:
    get:
      operationId: get-api-version-saas-purchased-subscription-id
      parameters:
      - explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: subscription-id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: _sub
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: purchased
  /api/{version}/saas/unsubscribe:
    post:
      parameters:
      - example: "{{api_version}}"
        explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                id: <guid>
                activityId: <guid>
                publisherId: testpublisher
                offerId: testoffer
                planId: starter
                quantity: 1
                subscriptionId: <guid>
                timeStamp: 2022-03-10T16:34:41.137017Z
                action: Suspend
                status: Succeeded
                operationRequestSource: Azure
                subscription:
                  id: <guid>
                  name: testcms
                  publisherId: testpublisher
                  offerId: cmstestoffer
                  planId: starter
                  quantity: null
                  beneficiary:
                    emailId: XXX
                    objectId: <guid>
                    tenantId: <guid>
                    puid: XXX
                  purchaser:
                    emailId: XXX
                    objectId: <guid>
                    tenantId: <guid>
                    puid: XXX
                  allowedCustomerOperations:
                  - Delete
                  - Update
                  - Read
                  sessionMode: None
                  isFreeTrial: false
                  isTest: false
                  sandboxType: None
                  saasSubscriptionStatus: Subscribed
                  term:
                    startDate: 2022-03-09T00:00:00Z
                    endDate: 2022-04-08T00:00:00Z
                    termUnit: P1M
                    chargeDuration: null
                  autoRenew: true
                  created: 2022-03-09T18:45:49.0735944Z
                  lastModified: 2022-03-09T22:49:25.4181451Z
                purchaseToken: null
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: unsubscribe POST
      tags:
      - default
components:
  schemas: {}
